# This is a basic workflow to help you get started with Actions

name: Test_Manual_Workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tapName:
        description: "Name of tap"
        required: true
      targetName:
        description: "Name of target"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "printInputs"
  printInputs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Print out the inputs
      - name: Print the inputs
        run: |
          echo "Tap Name: ${{ github.event.inputs.tapName }}"
          echo "Target Name: ${{ github.event.inputs.targetName }}"
